Fix: Adjust Travis configuration and require build for HHVM to pass
tomphp/config-service-provider pull request #86
Opened 2017-02-20 16:44 UTC by localheinz

This PR

* [x] adjusts the Travis configuration and requires the build for HHVM to pass

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.travis.yml#L33-L42).

2017-02-20 17:11 UTC, localheinz commented
Ha!

https://travis-ci.org/tomphp/container-configurator/jobs/203518123#L758-L760

2017-02-20 17:14 UTC, localheinz commented on src/Configurator.php
> -    ];
Ha, I think that is a BC break, right?

2017-02-20 20:44 UTC, tomphp commented on src/Configurator.php
> -    ];
Indeed it is, but I think HHVM support would be an acceptable reason to for a new major release right? I think it's also very unlikely that anyone is currently accessing these constants directly so it shouldn't affect anyone.

There are also some BC breaking changes I was hoping to make to the API in a major release at some point, but maybe that can be in a release - I can elaborate further if you are interested though?

2017-02-20 21:47 UTC, localheinz commented on src/Configurator.php
> -    ];
Absolutely, @tomphp!

2017-02-20 22:01 UTC, tomphp requested changes
Get Travis green for HHVM - then we can review the BC breaks.

2019-09-17 15:45 UTC, localheinz commented
@tomphp 

Do you have any interest in getting this merged? Otherwise I would close it!

👍

2019-09-19 08:16 UTC, tomphp commented
@localheinz I am interested but incredibly busy this week, I'll take a look next week if that's ok?

2020-03-06 23:12 UTC, closed without merging